<?php
/**
    This file is generated by the Prails Web Framework. All contents of this file
    do not need to adapt the GPL of the Prails Web Framework and are not under 
    any license as long as the contents do not declare it explicitly.
    
    Prails Web Framework is Copyright (C) 2010  Robert Kunze
*/

/*<CONFIGURATION>*/
/*</CONFIGURATION>*/

/*<LIBRARIES>*/
/*</LIBRARIES>*/

include "modules/empty/empty_printer.php";
include "modules/empty/empty_data.php";
include "modules/empty/empty_handler.php";

?>
