<?php
/**
    This file is generated by the Prails Web Framework. All contents of this file
    do not need to adapt the GPL of the Prails Web Framework and are not under 
    any license as long as the contents do not declare it explicitly.
    
    Prails Web Framework is Copyright (C) 2010  Robert Kunze
*/

class EmptyHandler extends AbstractHandler
{

   function EmptyHandler($str_lang = "")
   {
      $this->obj_data = new EmptyData();
      $this->str_lang = $str_lang;
      $this->gen = Generator::getInstance();
      $this->obj_print = new EmptyPrinter($str_lang);
	  $this->obj_parent = $this;		// by default each module is it's own parent
   }
   
   /*<EVENT-HANDLERS>*/
   /*</EVENT-HANDLERS>*/
}

?>